# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 05:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinobi_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(default='Window 10', max_length=100)),
                ('ram', models.IntegerField()),
                ('tester', models.CharField(max_length=100)),
                ('test_date', models.DateTimeField(default=datetime.datetime(2017, 7, 27, 5, 43, 38, 881119))),
                ('brower', models.CharField(default='Chrome', max_length=100)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinobi_api.Page')),
            ],
            options={
                'db_table': 'shinobi_test',
            },
        ),
    ]
