# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shinobi_api', '0002_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='brower',
            new_name='browser',
        ),
        migrations.AlterField(
            model_name='test',
            name='test_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
