# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinobi_api', '0003_auto_20170727_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='page',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
