# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-21 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinobi_api', '0004_auto_20170727_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
